### YamlMime:ManagedReference
items:
- uid: cqhttp.Cyan.Config
  commentId: T:cqhttp.Cyan.Config
  id: Config
  parent: cqhttp.Cyan
  children:
  - cqhttp.Cyan.Config.apiToken
  - cqhttp.Cyan.Config.isSendJson
  - cqhttp.Cyan.Config.matchCqCode
  - cqhttp.Cyan.Config.networkMaxFailure
  - cqhttp.Cyan.Config.paramCqCode
  - cqhttp.Cyan.Config.parseCqCode
  - cqhttp.Cyan.Config.SetToken(System.String)
  - cqhttp.Cyan.Config.timeOut
  langs:
  - csharp
  - vb
  name: Config
  nameWithType: Config
  fullName: cqhttp.Cyan.Config
  type: Class
  source:
    remote:
      path: src/Config.cs
      branch: master
      repo: https://github.com/frankli0324/cqhttp.Cyan.git
    id: Config
    path: src/Config.cs
    startLine: 4
  assemblies:
  - cqhttp.Cyan
  namespace: cqhttp.Cyan
  summary: 全局设置
  example: []
  syntax:
    content: public class Config
    content.vb: Public Class Config
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: cqhttp.Cyan.Config.isSendJson
  commentId: F:cqhttp.Cyan.Config.isSendJson
  id: isSendJson
  parent: cqhttp.Cyan.Config
  langs:
  - csharp
  - vb
  name: isSendJson
  nameWithType: Config.isSendJson
  fullName: cqhttp.Cyan.Config.isSendJson
  type: Field
  source:
    remote:
      path: src/Config.cs
      branch: master
      repo: https://github.com/frankli0324/cqhttp.Cyan.git
    id: isSendJson
    path: src/Config.cs
    startLine: 7
  assemblies:
  - cqhttp.Cyan
  namespace: cqhttp.Cyan
  summary: 消息默认发送格式
  example: []
  syntax:
    content: public static bool isSendJson
    return:
      type: System.Boolean
    content.vb: Public Shared isSendJson As Boolean
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: cqhttp.Cyan.Config.networkMaxFailure
  commentId: F:cqhttp.Cyan.Config.networkMaxFailure
  id: networkMaxFailure
  parent: cqhttp.Cyan.Config
  langs:
  - csharp
  - vb
  name: networkMaxFailure
  nameWithType: Config.networkMaxFailure
  fullName: cqhttp.Cyan.Config.networkMaxFailure
  type: Field
  source:
    remote:
      path: src/Config.cs
      branch: master
      repo: https://github.com/frankli0324/cqhttp.Cyan.git
    id: networkMaxFailure
    path: src/Config.cs
    startLine: 12
  assemblies:
  - cqhttp.Cyan
  namespace: cqhttp.Cyan
  summary: 网络错误时最多重试的次数
  example: []
  syntax:
    content: public const int networkMaxFailure = 3
    return:
      type: System.Int32
    content.vb: Public Const networkMaxFailure As Integer = 3
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: cqhttp.Cyan.Config.timeOut
  commentId: F:cqhttp.Cyan.Config.timeOut
  id: timeOut
  parent: cqhttp.Cyan.Config
  langs:
  - csharp
  - vb
  name: timeOut
  nameWithType: Config.timeOut
  fullName: cqhttp.Cyan.Config.timeOut
  type: Field
  source:
    remote:
      path: src/Config.cs
      branch: master
      repo: https://github.com/frankli0324/cqhttp.Cyan.git
    id: timeOut
    path: src/Config.cs
    startLine: 14
  assemblies:
  - cqhttp.Cyan
  namespace: cqhttp.Cyan
  summary: 网络请求超时秒数
  example: []
  syntax:
    content: public const int timeOut = 5
    return:
      type: System.Int32
    content.vb: Public Const timeOut As Integer = 5
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: cqhttp.Cyan.Config.apiToken
  commentId: F:cqhttp.Cyan.Config.apiToken
  id: apiToken
  parent: cqhttp.Cyan.Config
  langs:
  - csharp
  - vb
  name: apiToken
  nameWithType: Config.apiToken
  fullName: cqhttp.Cyan.Config.apiToken
  type: Field
  source:
    remote:
      path: src/Config.cs
      branch: master
      repo: https://github.com/frankli0324/cqhttp.Cyan.git
    id: apiToken
    path: src/Config.cs
    startLine: 17
  assemblies:
  - cqhttp.Cyan
  namespace: cqhttp.Cyan
  summary: 调用API时的验证头
  example: []
  syntax:
    content: public static string apiToken
    return:
      type: System.String
    content.vb: Public Shared apiToken As String
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: cqhttp.Cyan.Config.matchCqCode
  commentId: F:cqhttp.Cyan.Config.matchCqCode
  id: matchCqCode
  parent: cqhttp.Cyan.Config
  langs:
  - csharp
  - vb
  name: matchCqCode
  nameWithType: Config.matchCqCode
  fullName: cqhttp.Cyan.Config.matchCqCode
  type: Field
  source:
    remote:
      path: src/Config.cs
      branch: master
      repo: https://github.com/frankli0324/cqhttp.Cyan.git
    id: matchCqCode
    path: src/Config.cs
    startLine: 20
  assemblies:
  - cqhttp.Cyan
  namespace: cqhttp.Cyan
  summary: 匹配CQ码
  example: []
  syntax:
    content: public static Regex matchCqCode
    return:
      type: System.Text.RegularExpressions.Regex
    content.vb: Public Shared matchCqCode As Regex
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: cqhttp.Cyan.Config.parseCqCode
  commentId: F:cqhttp.Cyan.Config.parseCqCode
  id: parseCqCode
  parent: cqhttp.Cyan.Config
  langs:
  - csharp
  - vb
  name: parseCqCode
  nameWithType: Config.parseCqCode
  fullName: cqhttp.Cyan.Config.parseCqCode
  type: Field
  source:
    remote:
      path: src/Config.cs
      branch: master
      repo: https://github.com/frankli0324/cqhttp.Cyan.git
    id: parseCqCode
    path: src/Config.cs
    startLine: 23
  assemblies:
  - cqhttp.Cyan
  namespace: cqhttp.Cyan
  summary: 匹配CQ码的类型
  example: []
  syntax:
    content: public static Regex parseCqCode
    return:
      type: System.Text.RegularExpressions.Regex
    content.vb: Public Shared parseCqCode As Regex
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: cqhttp.Cyan.Config.paramCqCode
  commentId: F:cqhttp.Cyan.Config.paramCqCode
  id: paramCqCode
  parent: cqhttp.Cyan.Config
  langs:
  - csharp
  - vb
  name: paramCqCode
  nameWithType: Config.paramCqCode
  fullName: cqhttp.Cyan.Config.paramCqCode
  type: Field
  source:
    remote:
      path: src/Config.cs
      branch: master
      repo: https://github.com/frankli0324/cqhttp.Cyan.git
    id: paramCqCode
    path: src/Config.cs
    startLine: 27
  assemblies:
  - cqhttp.Cyan
  namespace: cqhttp.Cyan
  summary: 匹配CQ码的参数
  example: []
  syntax:
    content: public static Regex paramCqCode
    return:
      type: System.Text.RegularExpressions.Regex
    content.vb: Public Shared paramCqCode As Regex
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: cqhttp.Cyan.Config.SetToken(System.String)
  commentId: M:cqhttp.Cyan.Config.SetToken(System.String)
  id: SetToken(System.String)
  parent: cqhttp.Cyan.Config
  langs:
  - csharp
  - vb
  name: SetToken(String)
  nameWithType: Config.SetToken(String)
  fullName: cqhttp.Cyan.Config.SetToken(System.String)
  type: Method
  source:
    remote:
      path: src/Config.cs
      branch: master
      repo: https://github.com/frankli0324/cqhttp.Cyan.git
    id: SetToken
    path: src/Config.cs
    startLine: 33
  assemblies:
  - cqhttp.Cyan
  namespace: cqhttp.Cyan
  summary: "\n设定调用api时的验证头\n"
  example: []
  syntax:
    content: public static void SetToken(string token)
    parameters:
    - id: token
      type: System.String
    content.vb: Public Shared Sub SetToken(token As String)
  overload: cqhttp.Cyan.Config.SetToken*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: cqhttp.Cyan
  commentId: N:cqhttp.Cyan
  name: cqhttp.Cyan
  nameWithType: cqhttp.Cyan
  fullName: cqhttp.Cyan
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Text.RegularExpressions.Regex
  commentId: T:System.Text.RegularExpressions.Regex
  parent: System.Text.RegularExpressions
  isExternal: true
  name: Regex
  nameWithType: Regex
  fullName: System.Text.RegularExpressions.Regex
- uid: System.Text.RegularExpressions
  commentId: N:System.Text.RegularExpressions
  isExternal: true
  name: System.Text.RegularExpressions
  nameWithType: System.Text.RegularExpressions
  fullName: System.Text.RegularExpressions
- uid: cqhttp.Cyan.Config.SetToken*
  commentId: Overload:cqhttp.Cyan.Config.SetToken
  name: SetToken
  nameWithType: Config.SetToken
  fullName: cqhttp.Cyan.Config.SetToken
